const planetNine = [
	{
		number: 1,
		tasks: 1,
		description:
			'Congratulations! You have been chosen from a vast array of applicants to participate in the most important, and dangerous adventure that mankind has ever faced: the search for Planet Nine. You barely arrive at the training facility before you have already begun your first training phase: team building.',
	},
	{
		number: 2,
		tasks: 2,
		description:
			"It is apparent that you are a perfectly matched crew. Above all, is your mental connection - this so-called drift compatibility bodes well for an ongoing successful collaboration. It's time for training phases two and three: control technology and weightlessness.",
	},
	{
		number: 3,
		tasks: 2,
		taskTokens: [{ value: '1' }, { value: '2' }],
		description: '',
	},
	{
		number: 4,
		tasks: 3,
		description: '',
	},
	{
		number: 5,
		description: '',
	},
	{
		number: 6,
		tasks: 3,
		taskTokens: [{ value: '>' }, { value: '>>' }],
		description: '',
	},
	{
		number: 7,
		tasks: 3,
		taskTokens: [{ value: 'Ω' }],
		description: '',
	},
	{
		number: 8,
		tasks: 3,
		taskTokens: [{ value: '1' }, { value: '2' }, { value: '3' }],
		description: '',
	},
	{
		number: 9,
		description: '',
	},
	{
		number: 10,
		tasks: 4,
		description: '',
	},
	{
		number: 11,
		tasks: 4,
		taskTokens: [{ value: '1' }],
		description: '',
	},
	{
		number: 12,
		tasks: 4,
		taskTokens: [{ value: 'Ω' }],
		description: '',
	},
	{
		number: 13,
		description: '',
	},
	{
		number: 14,
		tasks: 4,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
		description: '',
	},
	{
		number: 15,
		tasks: 4,
		taskTokens: [{ value: '1' }, { value: '2' }, { value: '3' }, { value: '4' }],
		description: '',
	},
	{
		number: 16,
		description: '',
	},
	{
		number: 17,
		tasks: 2,
		taskTokens: [{ value: '>' }],
		description: '',
	},
	{
		number: 18,
		tasks: 5,
		description: '',
	},
	{
		number: 19,
		tasks: 5,
		taskTokens: [{ value: '1' }],
		description: '',
	},
	{
		number: 20,
		tasks: 2,
		description: '',
	},
	{
		number: 21,
		tasks: 5,
		taskTokens: [{ value: '1' }, { value: '2' }],
		description: '',
	},
	{
		number: 22,
		tasks: 5,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }, { value: '>>>>' }],
		description: '',
	},
	{
		number: 23,
		tasks: 5,
		taskTokens: [{ value: '1' }, { value: '2' }, { value: '3' }, { value: '4' }, { value: '5' }],
		description: '',
	},
	{
		number: 24,
		tasks: 6,
		description: '',
	},
	{
		number: 25,
		fivePlayerRule: true,
		tasks: 6,
		taskTokens: [{ value: '>' }, { value: '>>' }],
		description: '',
	},
	{
		number: 26,
		description: '',
	},
	{
		number: 27,
		fivePlayerRule: true,
		tasks: 3,
		description: '',
	},
	{
		number: 28,
		fivePlayerRule: true,
		tasks: 6,
		taskTokens: [{ value: '1' }, { value: 'Ω' }],
		description: '',
	},
	{
		number: 29,
		description: '',
	},
	{
		number: 30,
		fivePlayerRule: true,
		tasks: 6,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
		description: '',
	},
	{
		number: 31,
		fivePlayerRule: true,
		tasks: 6,
		taskTokens: [{ value: '1' }, { value: '2' }, { value: '3' }],
		description: '',
	},
	{
		number: 32,
		fivePlayerRule: true,
		tasks: 7,
		description: '',
	},
	{
		number: 33,
		description: '',
	},
	{
		number: 34,
		description: '',
	},
	{
		number: 35,
		fivePlayerRule: true,
		tasks: 7,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
	},
	{
		number: 36,
		fivePlayerRule: true,
		tasks: 7,
		taskTokens: [{ value: '1' }, { value: '2' }],
		description: '',
	},
	{
		number: 37,
		fivePlayerRule: true,
		tasks: 4,
		description: '',
	},
	{
		number: 38,
		fivePlayerRule: true,
		tasks: 8,
		description: '',
	},
	{
		number: 39,
		fivePlayerRule: true,
		tasks: 8,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
		description: '',
	},
	{
		number: 40,
		fivePlayerRule: true,
		tasks: 8,
		taskTokens: [{ value: '1' }, { value: '2' }, { value: '3' }],
		description: '',
	},
	{
		number: 41,
		description: '',
	},
	{
		number: 42,
		fivePlayerRule: true,
		tasks: 9,
		description: '',
	},
	{
		number: 43,
		fivePlayerRule: true,
		tasks: 9,
		description: '',
	},
	{
		number: 44,
		description: '',
	},
	{
		number: 45,
		fivePlayerRule: true,
		tasks: 9,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
		description: '',
	},
	{
		number: 46,
		description: '',
	},
	{
		number: 47,
		fivePlayerRule: true,
		tasks: 10,
		description: '',
	},
	{
		number: 48,
		fivePlayerRule: true,
		tasks: 3,
		taskTokens: [{ value: 'Ω' }],
		description: '',
	},
	{
		number: 49,
		fivePlayerRule: true,
		tasks: 10,
		taskTokens: [{ value: '>' }, { value: '>>' }, { value: '>>>' }],
		description: '',
	},
	{
		number: 50,
		description: '',
	},
]
module.exports = { planetNine }
